#!/usr/bin/env python3

from enum import Enum

# Not sure yet where these fit in, but they are used in the original code
# 0 = VOLTAGE_INFO
# 1 = COLOR_INFO
# 2 = SW_INFO



# The original code has a lot more color values, but I've only added the ones that
# are in use to this file
Imgproc_COLOR_RGB2YUV_YV12 = 131
Imgproc_COLOR_BGR2YUV_YV12 = 132

class EventType (Enum):
    UNKNOWN = (-1, -1)
    SUPPORT_FUNCTION_AND_VERSION_INFO = (0, 0)
    DEVICE_INFO_SERVICE = (0, 1)
    SUPPORT_FUNCTION_INFO = (0, 2)
    IDENTIFY_INFORMATION = (0, 16)
    SHUT_DOWN = (1, 0)
    RESET = (1, 1)
    AUTO_SLEEP_SETTINGS = (1, 2)
    BLE_CONNECT = (1, 3)
    PRINT_IMAGE_DOWNLOAD_START = (16, 0)
    PRINT_IMAGE_DOWNLOAD_DATA = (16, 1)
    PRINT_IMAGE_DOWNLOAD_END = (16, 2)
    PRINT_IMAGE_DOWNLOAD_CANCEL = (16, 3)
    PRINT_IMAGE = (16, 128)
    REJECT_FILM_COVER = (16, 129)
    FW_DOWNLOAD_START = (32, 0)
    FW_DOWNLOAD_DATA = (32, 1)
    FW_DOWNLOAD_END = (32, 2)
    FW_UPGRADE_EXIT = (32, 3)
    FW_PROGRAM_INFO = (32, 16)
    FW_DATA_BACKUP = (32, 128)
    FW_UPDATE_REQUEST = (32, 129)
    XYZ_AXIS_INFO = (48, 0)
    LED_PATTERN_SETTINGS = (48, 1)
    AXIS_ACTION_SETTINGS = (48, 2)
    LED_PATTERN_SETTINGS_DOUBLE = (48, 3)
    POWER_ONOFF_LED_SETTING = (48, 4)
    AR_LED_VIBRARTION_SETTING = (48, 6)
    ADDITIONAL_PRINTER_INFO = (48, 16)
    PRINTER_HEAD_LIGHT_CORRECT_INFO = (48, 128)
    PRINTER_HEAD_LIGHT_CORRECT_SETTINGS = (48, 129)
    CAMERA_SETTINGS = (128, 0)
    CAMERA_SETTINGS_GET = (128, 1)
    URL_UPLOAD_INFO = (129, 0)
    URL_PICTURE_UPLOAD_START = (129, 1)
    URL_PICTURE_UPLOAD = (129, 2)
    URL_PICTURE_UPLOAD_END = (129, 3)
    URL_AUDIO_UPLOAD_START = (129, 4)
    URL_AUDIO_UPLOAD = (129, 5)
    URL_AUDIO_UPLOAD_END = (129, 6)
    URL_UPLOAD_ADDRESS = (129, 7)
    URL_UPLOAD_DATA_COMPLETE = (129, 8)
    LIVE_VIEW_START = (130, 0)
    LIVE_VIEW_RECEIVE = (130, 1)
    LIVE_VIEW_STOP = (130, 2)
    LIVE_VIEW_TAKE_PICTURE = (130, 16)
    POST_VIEW_UPLOAD_START = (130, 32)
    POST_VIEW_UPLOAD = (130, 33)
    POST_VIEW_UPLOAD_END = (130, 34)
    POST_VIEW_PRINT = (130, 48)
    FRAME_PICTURE_DOWNLOAD_START = (Imgproc_COLOR_RGB2YUV_YV12, 0)
    FRAME_PICTURE_DOWNLOAD = (Imgproc_COLOR_RGB2YUV_YV12, 1)
    FRAME_PICTURE_DOWNLOAD_END = (Imgproc_COLOR_RGB2YUV_YV12, 2)
    FRAME_PICTURE_NAME_SETTING = (Imgproc_COLOR_RGB2YUV_YV12, 3)
    FRAME_PICTURE_NAME_GET = (Imgproc_COLOR_RGB2YUV_YV12, 4)
    CAMERA_LOG_SUBTOTAL_START = (Imgproc_COLOR_BGR2YUV_YV12, 0)
    CAMERA_LOG_SUBTOTAL_DATA = (Imgproc_COLOR_BGR2YUV_YV12, 1)
    CAMERA_LOG_SUBTOTAL_CLEAR = (Imgproc_COLOR_BGR2YUV_YV12, 2)
    CAMERA_LOG_DATE_START = (Imgproc_COLOR_BGR2YUV_YV12, 3)
    CAMERA_LOG_DATE_DATA = (Imgproc_COLOR_BGR2YUV_YV12, 4)
    CAMERA_LOG_DATE_CLEAR = (Imgproc_COLOR_BGR2YUV_YV12, 5)
    CAMERA_LOG_FILTER_START = (Imgproc_COLOR_BGR2YUV_YV12, 6)
    CAMERA_LOG_FILTER_DATA = (Imgproc_COLOR_BGR2YUV_YV12, 7)
    CAMERA_LOG_FILTER_CLEAR = (Imgproc_COLOR_BGR2YUV_YV12, 8);
